/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dsl;

import org.polarsys.capella.scenario.editor.dsl.TextualScenarioStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TextualScenarioStandaloneSetup extends TextualScenarioStandaloneSetupGenerated {
  public static void doSetup() {
    new TextualScenarioStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
