/*
 * generated by Xtext 2.10.0
 */
package org.polarsys.capella.scenario.editor.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.polarsys.capella.scenario.editor.dsl.ui.internal.DslActivator;

public class TextualScenarioUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.polarsys.capella.scenario.editor.dsl.TextualScenario");
	}

}
