/*******************************************************************************
 * Copyright (c) 2020 THALES GLOBAL SERVICES.
 *  
 *  This program and the accompanying materials are made available under the
 *  terms of the Eclipse Public License 2.0 which is available at
 *  http://www.eclipse.org/legal/epl-2.0
 *  
 *  SPDX-License-Identifier: EPL-2.0
 *  
 *  Contributors:
 *     Thales - initial API and implementation
 ******************************************************************************/
/**
 * generated by Xtext 2.10.0
 */
package org.polarsys.capella.scenario.editor.dsl.textualScenario;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lost Found Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.polarsys.capella.scenario.editor.dsl.textualScenario.LostFoundMessage#getArrow <em>Arrow</em>}</li>
 *   <li>{@link org.polarsys.capella.scenario.editor.dsl.textualScenario.LostFoundMessage#getDoubleDot <em>Double Dot</em>}</li>
 * </ul>
 *
 * @see org.polarsys.capella.scenario.editor.dsl.textualScenario.TextualScenarioPackage#getLostFoundMessage()
 * @model
 * @generated
 */
public interface LostFoundMessage extends Message
{
  /**
   * Returns the value of the '<em><b>Arrow</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arrow</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arrow</em>' attribute.
   * @see #setArrow(String)
   * @see org.polarsys.capella.scenario.editor.dsl.textualScenario.TextualScenarioPackage#getLostFoundMessage_Arrow()
   * @model
   * @generated
   */
  String getArrow();

  /**
   * Sets the value of the '{@link org.polarsys.capella.scenario.editor.dsl.textualScenario.LostFoundMessage#getArrow <em>Arrow</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arrow</em>' attribute.
   * @see #getArrow()
   * @generated
   */
  void setArrow(String value);

  /**
   * Returns the value of the '<em><b>Double Dot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Double Dot</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Double Dot</em>' attribute.
   * @see #setDoubleDot(String)
   * @see org.polarsys.capella.scenario.editor.dsl.textualScenario.TextualScenarioPackage#getLostFoundMessage_DoubleDot()
   * @model
   * @generated
   */
  String getDoubleDot();

  /**
   * Sets the value of the '{@link org.polarsys.capella.scenario.editor.dsl.textualScenario.LostFoundMessage#getDoubleDot <em>Double Dot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Double Dot</em>' attribute.
   * @see #getDoubleDot()
   * @generated
   */
  void setDoubleDot(String value);

} // LostFoundMessage
