/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.polarsys.capella.scenario.editor.dsl.TextualScenarioRuntimeModule;
import org.polarsys.capella.scenario.editor.dsl.TextualScenarioStandaloneSetup;
import org.polarsys.capella.scenario.editor.dsl.ide.TextualScenarioIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TextualScenarioIdeSetup extends TextualScenarioStandaloneSetup {
  @Override
  public Injector createInjector() {
    TextualScenarioRuntimeModule _textualScenarioRuntimeModule = new TextualScenarioRuntimeModule();
    TextualScenarioIdeModule _textualScenarioIdeModule = new TextualScenarioIdeModule();
    return Guice.createInjector(Modules2.mixin(_textualScenarioRuntimeModule, _textualScenarioIdeModule));
  }
}
