/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Activity</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage#getActivity()
 * @model
 * @generated
 */
public interface Activity extends GenericFunction
{
} // Activity
