/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arm Timer Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.polarsys.capella.scenario.editor.dslscenario.dsl.ArmTimerMessage#getParticipant <em>Participant</em>}</li>
 * </ul>
 *
 * @see org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage#getArmTimerMessage()
 * @model
 * @generated
 */
public interface ArmTimerMessage extends Message
{
  /**
   * Returns the value of the '<em><b>Participant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participant</em>' attribute.
   * @see #setParticipant(String)
   * @see org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage#getArmTimerMessage_Participant()
   * @model
   * @generated
   */
  String getParticipant();

  /**
   * Sets the value of the '{@link org.polarsys.capella.scenario.editor.dslscenario.dsl.ArmTimerMessage#getParticipant <em>Participant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Participant</em>' attribute.
   * @see #getParticipant()
   * @generated
   */
  void setParticipant(String value);

} // ArmTimerMessage
