/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Message</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage#getDeleteMessage()
 * @model
 * @generated
 */
public interface DeleteMessage extends SequenceMessageType
{
} // DeleteMessage
