/**
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.dsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.polarsys.capella.scenario.editor.dslscenario.dsl.DslPackage;
import org.polarsys.capella.scenario.editor.dslscenario.dsl.GenericComponent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Generic Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GenericComponentImpl extends ParticipantImpl implements GenericComponent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GenericComponentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.GENERIC_COMPONENT;
  }

} //GenericComponentImpl
