/*
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dslscenario.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.polarsys.capella.scenario.editor.dslscenario.ui.internal.DslscenarioActivator;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslscenarioActivator.getInstance().getInjector("org.polarsys.capella.scenario.editor.dslscenario.Dsl");
	}

}
