/*
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dsl.ide


/**
 * Use this class to register ide components.
 */
class TextualScenarioIdeModule extends AbstractTextualScenarioIdeModule {
}
