/*
 * generated by Xtext 2.18.0.M3
 */
package org.polarsys.capella.scenario.editor.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TextualScenarioStandaloneSetup extends TextualScenarioStandaloneSetupGenerated {

	def static void doSetup() {
		new TextualScenarioStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
